USE `sql6586800`;


DROP TABLE IF EXISTS `MEMBER`;

CREATE TABLE `MEMBER` (
  `MEMBERID` varchar(30) NOT NULL,
  `NAME` varchar(30) DEFAULT NULL,
  `TYPE` tinyint DEFAULT NULL,
  PRIMARY KEY (`MEMBERID`)
) ;


LOCK TABLES `MEMBER` WRITE;
INSERT INTO `MEMBER` VALUES ('E001','Hasitha',1);
UNLOCK TABLES;



DROP TABLE IF EXISTS `USER`;

CREATE TABLE `USER` (
  `USERID` varchar(30) NOT NULL,
  `EMAIL` varchar(30) DEFAULT NULL,
  `PASSWORD` varchar(100) DEFAULT NULL,
  `LOGGED_AT` datetime DEFAULT NULL,
  `REFRESH_TOKEN` varchar(255) DEFAULT NULL,
  UNIQUE KEY `REFRESH_TOKEN_UNIQUE` (`REFRESH_TOKEN`),
  KEY `userID_ibfk_1` (`USERID`),
  UNIQUE  (`USERID`),
  CONSTRAINT `userID_ibfk_1` FOREIGN KEY (`USERID`) REFERENCES `MEMBER` (`MEMBERID`)
) ;


LOCK TABLES `USER` WRITE;

INSERT INTO `USER` VALUES ('E001','hasitha.19@cse.mrt.ac.lk','$2a$04$eVtKkTCK7qJ4dlVzndMnX.kDDK0tFFz6CS.j1whZPrn/1wZQfz9IG',NULL,NULL);

UNLOCK TABLES;

